---
title: "Code Appendix
"
author: "Kashaun Eghdam, Ankhee Paul, Timothy Regis, Chen Shupeng"
date: "10/19/2020"
output: pdf_document
---

```{r, include = FALSE}
# Load Required Packages, use install.packages() if needed
library(tidyverse)
library(janitor)
library(dplyr)
library(MASS)
library(survey)
library(jtools)
library(broom.mixed)
library(ResourceSelection)
library(boot)
library(ggstance)
```

```{r}
# Read in dataset
gss <- read_csv('gss.csv')
```

```{r}
# Preview Dataset
head(gss)
```

```{r}
# Plot Bar for age distribution 
gss %>% 
  ggplot(aes(x=age)) + 
  geom_bar(colour="black", fill = 'blue') + 
  scale_x_binned(name="age") + 
  labs(x = 'Age', 
       y="Number of Respondents",
       title="Graph 1: Age Distribution Among Respondents",
       caption= "Source: Statistics Canada. (2017). General social survey(GSS)") + 
  theme_minimal()
```

```{r}
# Plot distribution of Total children
gss %>% ggplot(aes(x=total_children)) +
  geom_bar(colour="black", fill = 'blue') + 
  labs(y="Number of people",
       title="Graph 2: Total children distribution among respondents", 
       caption= "Source:Statistics Canada. (2017). General social survey (GSS)") + 
  theme_minimal()
```

```{r, warning = FALSE}
# Create a table of proportions of income levels
gss %>% 
  group_by(income_respondent) %>% 
  summarise('number'=n(),"percentage"=n()/nrow(gss))
```

```{r}
# Create a table of proportions of education levels
gss %>% 
  group_by(education) %>% 
  summarise('number'=n(),"percentage"=n()/nrow(gss))
```

```{r}
# Select variables of interest and filter out NA responses
gss_test <- gss
gss_test1 <- gss_test %>%
  dplyr::select(caseid, total_children, age,
         income_respondent, education)

gss_test2 <- gss_test1 %>% 
  na.omit() %>%
  filter(education != 'NA')

head(gss_test2)
mean(gss_test2$total_children)
var(gss_test2$total_children)
```

```{r, warning = FALSE}
# Splicing Data into Testing and Training Set
set.seed(140)
gss_sample <- sample_n(gss_test2, 4000)
gss_test2_MSPE <- gss_test2 %>%
  anti_join(gss_sample)
length(gss_test2_MSPE$caseid)
```

```{r}
# Generation of Regression Model
negbinmodel <- glm.nb(total_children ~ age + 
                        as.factor(education) + 
                        as.factor(income_respondent), 
                      data = gss_test2_MSPE)
```

```{r}
#Model validation, comparing MSPE and MSres
# fitting sample dataset to our model
gss_sample_glm <- glm.nb(total_children ~ age + 
                        as.factor(education) + 
                        as.factor(income_respondent),  
                      data = gss_sample)
                      
#calculation of the mspe for sample dataset
mspe = sum(resid(gss_sample_glm)^2)/ length(gss_sample$total_children)
#calculation of the MSres for our main dataset
msres = sum(resid(negbinmodel)^2)/(length(gss_test2_MSPE$total_children) - 13)
mspe
msres
```

```{r,include = FALSE}
# Compute 10-Fold Cross-Validation Prediction Error
cv.glm(gss_test2_MSPE, negbinmodel, K = 10)
```

```{r}
# Display Summary Statistics of Regression Model
summary(negbinmodel)
```

```{r}
# Cleaner Display of Summary Statitics for Report 
summ(negbinmodel, digits = 5, model.fit = FALSE)
```

```{r}
# Plot Graph of Predictor Estimates and Standard Deviations
plot_summs(negbinmodel, scale= FALSE)
```
































