---
title: "STA304PS3-ModelCoding"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load Required Packages, Install if needed
library(tidyverse)
library(dplyr)
library(MASS)
library(survey)
library(jtools)
library(broom.mixed)
library(ggstance)
```

```{r}
# Call Dataset
gss <- read_csv("gss.csv")
```


## Model

```{r}
# Selecting chosen variables and filtering out NA responses
gss_t <- gss %>%
  dplyr::select(caseid,total_children, age,
         income_respondent, education)

gss_clean <- gss_t %>% na.omit()
head(gss_clean)

# pulling a random sample of 4000 observations from our 
# main dataset to use later for model validation
set.seed(140)
gss_sample <- sample_n(gss_clean, 4000)

# we will be taking the 4000 observation sample out of the datset
# and use the remaining data for model development 
gss_clean1 <- gss_clean %>% anti_join(gss_sample)
```

```{r}
# First Design of GLM Regression Model
gss_glm <- glm.nb(total_children ~ age + 
                        as.factor(education) + 
                        as.factor(income_respondent), 
                      data = gss_clean1)
```

```{r}
# Display Summary Statistics of Model
summary(gss_glm)
```

```{r}
# Slightly cleaner looking display of summary statistics
summ(gss_glm, vifs = TRUE, digits = 5, model.fit = FALSE)
```

```{r}
# Plot displaying estimated coefficient values + their respective standard deviation
plot_summs(gss_glm, scale= FALSE)
```

```{r}
#Model validation, comparing MSPE and MSres

# fitting sample dataset to our model
gss_sample_glm <- glm.nb(total_children ~ age + 
                        as.factor(education) + 
                        as.factor(income_respondent),  
                      data = gss_sample)
                      
#calculation of the mspe for smaple dataset
mspe = sum(resid(gss_sample_glm)^2)/ length(gss_sample$total_children)

#calculation of the MSres for our main dataset
msres = sum(resid(gss_glm)^2)/(length(gss_clean1$total_children) - 13) 
```
