% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={STA304PS3RoughR2},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{STA304PS3RoughR2}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching packages --------------------------------------- tidyverse 1.3.0 --
\end{verbatim}

\begin{verbatim}
## v ggplot2 3.3.2     v purrr   0.3.4
## v tibble  3.0.4     v dplyr   1.0.2
## v tidyr   1.1.2     v stringr 1.4.0
## v readr   1.4.0     v forcats 0.5.0
\end{verbatim}

\begin{verbatim}
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(janitor)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'janitor'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     chisq.test, fisher.test
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(dplyr)}
\KeywordTok{library}\NormalTok{(MASS)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'MASS'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:dplyr':
## 
##     select
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(survey)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: grid
\end{verbatim}

\begin{verbatim}
## Loading required package: Matrix
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'Matrix'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:tidyr':
## 
##     expand, pack, unpack
\end{verbatim}

\begin{verbatim}
## Loading required package: survival
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'survey'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:graphics':
## 
##     dotchart
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(jtools)}
\KeywordTok{library}\NormalTok{(broom.mixed)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Registered S3 method overwritten by 'broom.mixed':
##   method      from 
##   tidy.gamlss broom
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ResourceSelection)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## ResourceSelection 0.3-5   2019-07-22
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(boot)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'boot'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:survival':
## 
##     aml
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ggstance)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'ggstance'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:ggplot2':
## 
##     geom_errorbarh, GeomErrorbarh
\end{verbatim}

\hypertarget{abstract}{%
\subsection{Abstract}\label{abstract}}

\hypertarget{introduction}{%
\subsection{Introduction}\label{introduction}}

The Canadian General Social Survey is a program conducted by Statistics
Canada that aims to gather data through a series of annually
independent, cross-sectional surveys, on social trends, exploring
specific themes in depth. The objective is to monitor changes in the
living conditions of Canadian citizens, and provide information on key
social policy issues. Initially, using the Random Digit Dialling method
to gather data from Canadian citizens aged 15 years and over, living in
private households in each of the provinces, the mode of collection has
now changed to Computer Assisted Telephone Interviewing and internet
questionnaires.

The GSS focuses on several specific themes such as caregiving and care
receiving and families, to name a few. It is quite common for
individuals to determine their family size based on their earning
capacity and age. Higher levels of maturity as well as education
inclines towards practical family planning, especially on the part of
the present generation. In this paper, we aim to explore the independent
variables such as education, income and age and their relationship with
regards to the total children in a family. We are using a negative
binomial distribution in order to create an appropriate regression model
with our cleaned data, obtained from the GSS dataset. This model will
aid the understanding of the current social trends involving family
planning and its determinants.

\hypertarget{data-discussion}{%
\subsection{Data Discussion}\label{data-discussion}}

The data we used in this paper were collected by Canadian General Social
Survey Program back in 2017. The 2017 GSS is a sample survey with
cross-sectional design. The target population includes all
non-institutionalized persons 15 years of age and older, living in the
10 provinces of Canada. This survey included more than 400 variables
ranging from educational background to demographic characteristics.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gss <-}\StringTok{ }\KeywordTok{read_csv}\NormalTok{(}\StringTok{'gss.csv'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## -- Column specification --------------------------------------------------------
## cols(
##   .default = col_character(),
##   caseid = col_double(),
##   age = col_double(),
##   age_first_child = col_double(),
##   age_youngest_child_under_6 = col_double(),
##   total_children = col_double(),
##   age_start_relationship = col_double(),
##   age_at_first_marriage = col_double(),
##   age_at_first_birth = col_double(),
##   distance_between_houses = col_double(),
##   age_youngest_child_returned_work = col_double(),
##   feelings_life = col_double(),
##   hh_size = col_double(),
##   number_total_children_intention = col_double(),
##   number_marriages = col_double(),
##   fin_supp_child_supp = col_double(),
##   fin_supp_child_exp = col_double(),
##   fin_supp_lump = col_double(),
##   fin_supp_other = col_double(),
##   is_male = col_double(),
##   main_activity = col_logical()
##   # ... with 1 more columns
## )
## i Use `spec()` for the full column specifications.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(gss)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 81
##   caseid   age age_first_child age_youngest_ch~ total_children age_start_relat~
##    <dbl> <dbl>           <dbl>            <dbl>          <dbl>            <dbl>
## 1      1  52.7              27               NA              1             NA  
## 2      2  51.1              33               NA              5             NA  
## 3      3  63.6              40               NA              5             NA  
## 4      4  80                56               NA              1             NA  
## 5      5  28                NA               NA              0             25.3
## 6      6  63                37               NA              2             NA  
## # ... with 75 more variables: age_at_first_marriage <dbl>,
## #   age_at_first_birth <dbl>, distance_between_houses <dbl>,
## #   age_youngest_child_returned_work <dbl>, feelings_life <dbl>, sex <chr>,
## #   place_birth_canada <chr>, place_birth_father <chr>,
## #   place_birth_mother <chr>, place_birth_macro_region <chr>,
## #   place_birth_province <chr>, year_arrived_canada <chr>, province <chr>,
## #   region <chr>, pop_center <chr>, marital_status <chr>, aboriginal <chr>,
## #   vis_minority <chr>, age_immigration <chr>, landed_immigrant <chr>,
## #   citizenship_status <chr>, education <chr>, own_rent <chr>,
## #   living_arrangement <chr>, hh_type <chr>, hh_size <dbl>,
## #   partner_birth_country <chr>, partner_birth_province <chr>,
## #   partner_vis_minority <chr>, partner_sex <chr>, partner_education <chr>,
## #   average_hours_worked <chr>, worked_last_week <chr>,
## #   partner_main_activity <chr>, self_rated_health <chr>,
## #   self_rated_mental_health <chr>, religion_has_affiliation <chr>,
## #   regilion_importance <chr>, language_home <chr>, language_knowledge <chr>,
## #   income_family <chr>, income_respondent <chr>, occupation <chr>,
## #   childcare_regular <chr>, childcare_type <chr>,
## #   childcare_monthly_cost <chr>, ever_fathered_child <chr>,
## #   ever_given_birth <chr>, number_of_current_union <chr>,
## #   lives_with_partner <chr>, children_in_household <chr>,
## #   number_total_children_intention <dbl>, has_grandchildren <chr>,
## #   grandparents_still_living <chr>, ever_married <chr>,
## #   current_marriage_is_first <chr>, number_marriages <dbl>,
## #   religion_participation <chr>, partner_location_residence <chr>,
## #   full_part_time_work <chr>, time_off_work_birth <chr>,
## #   reason_no_time_off_birth <chr>, returned_same_job <chr>,
## #   satisfied_time_children <chr>, provide_or_receive_fin_supp <chr>,
## #   fin_supp_child_supp <dbl>, fin_supp_child_exp <dbl>, fin_supp_lump <dbl>,
## #   fin_supp_other <dbl>, fin_supp_agreement <chr>,
## #   future_children_intention <chr>, is_male <dbl>, main_activity <lgl>,
## #   age_diff <chr>, number_total_children_known <dbl>
\end{verbatim}

To carry out sampling, each of the ten provinces were divided into
strata (i.e., geographic areas). Many of the Census Metropolitan Areas
(CMAs) were each considered separate strata. Compared with the previous
survey, the advantages of the 2017 GSS survey are many survey specific
socio-demographic questions were replaced by Statistics Canada's
harmonized content questions (i.e., standardized modules for household
survey variables, such as marital status, education, and labour force)
and the 2017 GSS on Families uses the redesigned GSS frame, which
integrates data from sources of telephone numbers (landline and
cellular) available to Statistics Canada and the Address Register.

In addition, the non-response problem was well handled . The
non-response adjustment was done in three stages. In the first stage,
adjustments were made for complete non-response. This was done within
each stratum. In the second stage, adjustments were made for
non-response with auxiliary information from sources available to
Statistics Canada. These households had some auxiliary information which
was used to model propensity to respond. In the third stage, adjustments
were made for partial non-response. These households had some auxiliary
information which was used to model propensity to respond.

However, most of the variables needed to be understood in the survey
dictionary, so with the help of Professor Rohan Alexander, we reduced
the number of variables we were interested in to 81.In this paper, we
will focus on the three variables: age, income, and education and we
want to determine the relationship between these three variables and
total number of children in a family.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{## age ditribution }
\NormalTok{gss }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{age)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{colour=}\StringTok{"black"}\NormalTok{, }\DataTypeTok{fill =} \StringTok{'blue'}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{scale_x_binned}\NormalTok{(}\DataTypeTok{name=}\StringTok{"age"}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \StringTok{'Age'}\NormalTok{, }
       \DataTypeTok{y=}\StringTok{"Number of Respondents"}\NormalTok{,}
       \DataTypeTok{title=}\StringTok{"Graph 1: Age Distribution Among Respondents"}\NormalTok{,}
       \DataTypeTok{caption=} \StringTok{"Source: Statistics Canada. (2017). General social survey(GSS)"}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{theme_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{STA304PS3Rough3_files/figure-latex/unnamed-chunk-3-1.pdf}

As shown in graph 1, the largest proportion of respondents were over the
age of 50, with the highest number of respondents between the ages of 60
to 70. In contrast, we see the smallest number of respondents below the
age of 20. Thus, the proportion of older respondents greatly outweighs
the proportion of younger respondents to the the survey. Older
respondents have often reached the final number of children they will
have, whereas the younger proportion will likely parent more children in
the future. This may cause some disruptions to our model's strength as
younger respondents with similar degrees and income levels to older
respondents will likely have different numbers of children. As a result
of this, we may see a slight underestimation of the strengths of these
predictors.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Total children distribution}
\NormalTok{gss }\OperatorTok{%>%}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{total_children)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{colour=}\StringTok{"black"}\NormalTok{, }\DataTypeTok{fill =} \StringTok{'blue'}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{y=}\StringTok{"Number of people"}\NormalTok{,}
       \DataTypeTok{title=}\StringTok{"Graph 2: Total children distribution among respondents"}\NormalTok{, }
       \DataTypeTok{caption=} \StringTok{"Source:Statistics Canada. (2017). General social survey (GSS)"}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{theme_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 19 rows containing non-finite values (stat_count).
\end{verbatim}

\includegraphics{STA304PS3Rough3_files/figure-latex/unnamed-chunk-4-1.pdf}

From graph 2, we can clearly see that most respondents have zero or two
children with proportions over 30\%. As expected, the lowest proportion
of respondents are seen with 4 or more children. The large number of
respondents with zero children is surprising given the age proportions
we saw earlier, however, this should not disturb our model's ability.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# income distribution}
\NormalTok{gss }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(income_respondent) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\StringTok{'number'}\NormalTok{=}\KeywordTok{n}\NormalTok{(),}\StringTok{"percentage"}\NormalTok{=}\KeywordTok{n}\NormalTok{()}\OperatorTok{/}\KeywordTok{nrow}\NormalTok{(gss))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` ungrouping output (override with `.groups` argument)
\end{verbatim}

\begin{verbatim}
## # A tibble: 6 x 3
##   income_respondent     number percentage
##   <chr>                  <int>      <dbl>
## 1 $100,000 to $ 124,999    846     0.0411
## 2 $125,000 and more        885     0.0430
## 3 $25,000 to $49,999      6173     0.300 
## 4 $50,000 to $74,999      3896     0.189 
## 5 $75,000 to $99,999      2030     0.0985
## 6 Less than $25,000       6772     0.329
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# education distribution}
\NormalTok{gss }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(education) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\StringTok{'number'}\NormalTok{=}\KeywordTok{n}\NormalTok{(),}\StringTok{"percentage"}\NormalTok{=}\KeywordTok{n}\NormalTok{()}\OperatorTok{/}\KeywordTok{nrow}\NormalTok{(gss))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` ungrouping output (override with `.groups` argument)
\end{verbatim}

\begin{verbatim}
## # A tibble: 8 x 3
##   education                                                    number percentage
##   <chr>                                                         <int>      <dbl>
## 1 Bachelor's degree (e.g. B.A., B.Sc., LL.B.)                    3753     0.182 
## 2 College, CEGEP or other non-university certificate or di...    4566     0.222 
## 3 High school diploma or a high school equivalency certificate   4848     0.235 
## 4 Less than high school diploma or its equivalent                3036     0.147 
## 5 Trade certificate or diploma                                   1483     0.0720
## 6 University certificate or diploma below the bachelor's level    732     0.0355
## 7 University certificate, diploma or degree above the bach...    1843     0.0895
## 8 <NA>                                                            341     0.0166
\end{verbatim}

As shown in table 3 and table 4, nearly a third of respondents earn less
than 25,000 a year, with the next highest proportion seen earning
between 25,000 and 49,999, while only 4 percent earn more than 125,000 a
year. As for educational background, more than 50\% of respondents had a
college diploma or above, and only about 15 per cent had a lower
educational level than high school level. We may end up running into
problems with our model's statistical significance for the categories
with the lowest proportions of respondents as there will be less data
for our model to get a clear understanding of. This will likely result
in these income and education options being less significant than their
alternatives in determining expected number of children.

\hypertarget{model-development}{%
\subsection{Model Development}\label{model-development}}

Due to this being a real survey, we can find many NA values in the
responses that can prevent us from properly carrying out a regression
analysis. To correct this we first selected only the variables of
interest (total number of children, age, education, and respondent
income) from our original data and made a new dataset of these. We then
filtered the responses to these questions so that they would contain
only complete cases and remove any NA responses. Doing this ensures that
the length of our regression model's observations would match that of
our cleaned dataset.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gss_test <-}\StringTok{ }\NormalTok{gss}
\NormalTok{gss_test1 <-}\StringTok{ }\NormalTok{gss_test }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{select}\NormalTok{(total_children, age,}
\NormalTok{         income_respondent, education)}

\NormalTok{gss_test2 <-}\StringTok{ }\NormalTok{gss_test1 }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{na.omit}\NormalTok{() }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(education }\OperatorTok{!=}\StringTok{ 'NA'}\NormalTok{)}

\KeywordTok{head}\NormalTok{(gss_test2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 4
##   total_children   age income_respondent  education                             
##            <dbl> <dbl> <chr>              <chr>                                 
## 1              1  52.7 $25,000 to $49,999 High school diploma or a high school ~
## 2              5  51.1 Less than $25,000  Trade certificate or diploma          
## 3              5  63.6 $25,000 to $49,999 Bachelor's degree (e.g. B.A., B.Sc., ~
## 4              1  80   $50,000 to $74,999 High school diploma or a high school ~
## 5              0  28   Less than $25,000  College, CEGEP or other non-universit~
## 6              2  63   Less than $25,000  High school diploma or a high school ~
\end{verbatim}

The regression model we have chosen to use in this study is a
generalized linear regression model of the negative binomial family. A
generalized linear model is a generalization of ordinary linear
regression which removes the assumptions made in the linear model. This
model then allows us to link our response variable through a specified
probability distribution, we refer to this distribution as the family of
our regression model. Thus, unlike in linear regression, we do not need
to have a normally distributed response variable, a requirement often
not met by real data like ours.

We first made this choice as the independent variable we are studying,
total children, is count based and not continuous which meant that
ordinary least squares regression would not work as well. Many of our
variables also violate the strong requirements for a linear regression
model like homoscedasticity and normality of errors. Since generalized
linear regression models do not feature these same requirements, this
made it the ideal model option for our data.

When it comes to determining a distribution family, the skewness of our
data suggests that a poisson distribution might be suitable since it
accounts for this. However, if we analyze the mean and variance of total
children Mean = \_\_\_ Variance = \_\_\_ we notice that the variance is
greater, meaning that our data is over dispersed. This violates the
poisson model's equal dispersion assumption and will negatively affect
the effectiveness of our model. As this equal dispersion assumption is
often unrealistic for real world data, we must use a probability
distribution similar to poisson in shape, but without the harsh
criterion. Thus, to account for this, we have decided to use a negative
binomial probability distribution in our model. A negative binomial
distribution shares almost the exact same shape as a poisson
distribution but it does not make the same equal dispersion assumption.
As it works well specifically with over-dispersed and skewed count data,
which is exactly what we have, we decided to use a generalized linear
regression model of the negative binomial family throughout our study.

Alternatively, at this step we could have chosen a zero inflated poisson
regression model as we notice the number of respondents with zero total
children is extremely large, at over 30\% of our dataset. We decided
against this, however, as we also see an almost equally large number of
respondents with a total of two children as well as the strong
overdispersion in our data which the zero inflated model could not
account for.

As mentioned earlier, the explanatory variables we have chosen for our
study are the respondent's; age, education, and income bracket, as they
are all extremely influential in determining one's social/economic
status which is known to play a key role in the number of children in a
family. Since age has already been recorded as a numerical value, we did
not have to alter it to fit it into our model. However, for both
education and respondent income, they are set up as categorical strings
in our data, thus to allow them to function properly in our generalized
linear model we first needed to apply the as.factor() function from the
base R package to convert them into a factor form we can work with.

Final Model Code

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{negbinmodel <-}\StringTok{ }\KeywordTok{glm.nb}\NormalTok{(total_children }\OperatorTok{~}\StringTok{ }\NormalTok{age }\OperatorTok{+}\StringTok{ }
\StringTok{                        }\KeywordTok{as.factor}\NormalTok{(education) }\OperatorTok{+}\StringTok{ }
\StringTok{                        }\KeywordTok{as.factor}\NormalTok{(income_respondent), }
                      \DataTypeTok{data =}\NormalTok{ gss_test2)}
\end{Highlighting}
\end{Shaded}

\hypertarget{model-validation}{%
\subsection{Model Validation}\label{model-validation}}

\hypertarget{cv.glmgss_test2-negbinmodel-k10}{%
\section{cv.glm(gss\_test2, negbinmodel,
K=10)}\label{cv.glmgss_test2-negbinmodel-k10}}

\hypertarget{section}{%
\section{{[}1{]} 1.795375 1.795206}\label{section}}

Using a 10-fold cross validation analysis, we find that our cross
validation estimate of prediction error is equal to 1.79.

This means

As a result of this relatively high value, our model's predictive
ability will not be extremely strong as the error will likely cause us
to under or overestimate the number of children we expect. This is
likely due to the number of predictor variables we have chosen to
include. These values suggest that there is still a lot of variance in
the total number of children a family has, given their responses to
these questions. By using more predictor variables we would be able to
gain a more specific understanding of exactly what personal factors will
result in the highest number of children in a family. Options we have
considered include; age of the respondent at the birth of their first
child, whether or not the respondent has a religious affiliation, and
whether or not the respondent is currently married. The addition of
these variables would require different regression models depending on
dispersion in the data and the distribution of the response variable.
While further research must be done to reach better predictive
abilities, the estimates and data we have collected will still be able
to tell us the relative significance of the response options and how
they affect the total number of children we expect to see.

\hypertarget{results}{%
\subsection{Results}\label{results}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(negbinmodel)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm.nb(formula = total_children ~ age + as.factor(education) + 
##     as.factor(income_respondent), data = gss_test2, init.theta = 23.45931506, 
##     link = log)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.6339  -1.1930  -0.0936   0.5871   3.8013  
## 
## Coefficients:
##                                                                                    Estimate
## (Intercept)                                                                      -0.8128885
## age                                                                               0.0241453
## as.factor(education)College, CEGEP or other non-university certificate or di...   0.1301247
## as.factor(education)High school diploma or a high school equivalency certificate  0.1232606
## as.factor(education)Less than high school diploma or its equivalent               0.1761728
## as.factor(education)Trade certificate or diploma                                  0.1855433
## as.factor(education)University certificate or diploma below the bachelor's level  0.0575405
## as.factor(education)University certificate, diploma or degree above the bach...  -0.0588998
## as.factor(income_respondent)$125,000 and more                                     0.0236864
## as.factor(income_respondent)$25,000 to $49,999                                   -0.1503147
## as.factor(income_respondent)$50,000 to $74,999                                   -0.0824145
## as.factor(income_respondent)$75,000 to $99,999                                    0.0025626
## as.factor(income_respondent)Less than $25,000                                    -0.1807441
##                                                                                  Std. Error
## (Intercept)                                                                       0.0352721
## age                                                                               0.0003577
## as.factor(education)College, CEGEP or other non-university certificate or di...   0.0188100
## as.factor(education)High school diploma or a high school equivalency certificate  0.0187801
## as.factor(education)Less than high school diploma or its equivalent               0.0208807
## as.factor(education)Trade certificate or diploma                                  0.0247376
## as.factor(education)University certificate or diploma below the bachelor's level  0.0325651
## as.factor(education)University certificate, diploma or degree above the bach...   0.0246317
## as.factor(income_respondent)$125,000 and more                                     0.0381568
## as.factor(income_respondent)$25,000 to $49,999                                    0.0299317
## as.factor(income_respondent)$50,000 to $74,999                                    0.0306478
## as.factor(income_respondent)$75,000 to $99,999                                    0.0329308
## as.factor(income_respondent)Less than $25,000                                     0.0301713
##                                                                                  z value
## (Intercept)                                                                      -23.046
## age                                                                               67.493
## as.factor(education)College, CEGEP or other non-university certificate or di...    6.918
## as.factor(education)High school diploma or a high school equivalency certificate   6.563
## as.factor(education)Less than high school diploma or its equivalent                8.437
## as.factor(education)Trade certificate or diploma                                   7.500
## as.factor(education)University certificate or diploma below the bachelor's level   1.767
## as.factor(education)University certificate, diploma or degree above the bach...   -2.391
## as.factor(income_respondent)$125,000 and more                                      0.621
## as.factor(income_respondent)$25,000 to $49,999                                    -5.022
## as.factor(income_respondent)$50,000 to $74,999                                    -2.689
## as.factor(income_respondent)$75,000 to $99,999                                     0.078
## as.factor(income_respondent)Less than $25,000                                     -5.991
##                                                                                  Pr(>|z|)
## (Intercept)                                                                       < 2e-16
## age                                                                               < 2e-16
## as.factor(education)College, CEGEP or other non-university certificate or di...  4.59e-12
## as.factor(education)High school diploma or a high school equivalency certificate 5.26e-11
## as.factor(education)Less than high school diploma or its equivalent               < 2e-16
## as.factor(education)Trade certificate or diploma                                 6.36e-14
## as.factor(education)University certificate or diploma below the bachelor's level  0.07724
## as.factor(education)University certificate, diploma or degree above the bach...   0.01679
## as.factor(income_respondent)$125,000 and more                                     0.53475
## as.factor(income_respondent)$25,000 to $49,999                                   5.12e-07
## as.factor(income_respondent)$50,000 to $74,999                                    0.00716
## as.factor(income_respondent)$75,000 to $99,999                                    0.93797
## as.factor(income_respondent)Less than $25,000                                    2.09e-09
##                                                                                     
## (Intercept)                                                                      ***
## age                                                                              ***
## as.factor(education)College, CEGEP or other non-university certificate or di...  ***
## as.factor(education)High school diploma or a high school equivalency certificate ***
## as.factor(education)Less than high school diploma or its equivalent              ***
## as.factor(education)Trade certificate or diploma                                 ***
## as.factor(education)University certificate or diploma below the bachelor's level .  
## as.factor(education)University certificate, diploma or degree above the bach...  *  
## as.factor(income_respondent)$125,000 and more                                       
## as.factor(income_respondent)$25,000 to $49,999                                   ***
## as.factor(income_respondent)$50,000 to $74,999                                   ** 
## as.factor(income_respondent)$75,000 to $99,999                                      
## as.factor(income_respondent)Less than $25,000                                    ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for Negative Binomial(23.4593) family taken to be 1)
## 
##     Null deviance: 30379  on 20243  degrees of freedom
## Residual deviance: 24882  on 20231  degrees of freedom
## AIC: 64195
## 
## Number of Fisher Scoring iterations: 1
## 
## 
##               Theta:  23.46 
##           Std. Err.:  3.67 
## 
##  2 x log-likelihood:  -64166.84
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summ}\NormalTok{(negbinmodel, }\DataTypeTok{vifs =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{digits =} \DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## MODEL INFO:
## Observations: 20244
## Dependent Variable: total_children
## Type: Generalized linear model
##   Family: Negative Binomial(23.4593) 
##   Link function: log 
## 
## MODEL FIT:
## χ²() = , p = 
## Pseudo-R² (Cragg-Uhler) = 0.22243
## Pseudo-R² (McFadden) = 0.07098
## AIC = 64194.83931, BIC = 64305.65790 
## 
## Standard errors: MLE
## -------------------------------------------------------------------------
##                                                Est.      S.E.      z val.
## ---------------------------------------- ---------- --------- -----------
## (Intercept)                                -0.81289   0.03527   -23.04625
## age                                         0.02415   0.00036    67.49285
## as.factor(education)College,                0.13012   0.01881     6.91785
## CEGEP or other non-university                                            
## certificate or di...                                                     
## as.factor(education)High                    0.12326   0.01878     6.56338
## school diploma or a high                                                 
## school equivalency                                                       
## certificate                                                              
## as.factor(education)Less                    0.17617   0.02088     8.43712
## than high school diploma or                                              
## its equivalent                                                           
## as.factor(education)Trade                   0.18554   0.02474     7.50044
## certificate or diploma                                                   
## as.factor(education)University              0.05754   0.03257     1.76694
## certificate or diploma below                                             
## the bachelor's level                                                     
## as.factor(education)University             -0.05890   0.02463    -2.39122
## certificate, diploma or degree                                           
## above the bach...                                                        
## as.factor(income_respondent)$125,000        0.02369   0.03816     0.62076
## and more                                                                 
## as.factor(income_respondent)$25,000        -0.15031   0.02993    -5.02192
## to $49,999                                                               
## as.factor(income_respondent)$50,000        -0.08241   0.03065    -2.68908
## to $74,999                                                               
## as.factor(income_respondent)$75,000         0.00256   0.03293     0.07782
## to $99,999                                                               
## as.factor(income_respondent)Less           -0.18074   0.03017    -5.99060
## than $25,000                                                             
## -------------------------------------------------------------------------
##  
## ------------------------------------------------------------
##                                                  p       VIF
## ---------------------------------------- --------- ---------
## (Intercept)                                0.00000          
## age                                        0.00000   1.06464
## as.factor(education)College,               0.00000   1.26776
## CEGEP or other non-university                               
## certificate or di...                                        
## as.factor(education)High                   0.00000   1.26776
## school diploma or a high                                    
## school equivalency                                          
## certificate                                                 
## as.factor(education)Less                   0.00000   1.26776
## than high school diploma or                                 
## its equivalent                                              
## as.factor(education)Trade                  0.00000   1.26776
## certificate or diploma                                      
## as.factor(education)University             0.07724   1.26776
## certificate or diploma below                                
## the bachelor's level                                        
## as.factor(education)University             0.01679   1.26776
## certificate, diploma or degree                              
## above the bach...                                           
## as.factor(income_respondent)$125,000       0.53475   1.21994
## and more                                                    
## as.factor(income_respondent)$25,000        0.00000   1.21994
## to $49,999                                                  
## as.factor(income_respondent)$50,000        0.00716   1.21994
## to $74,999                                                  
## as.factor(income_respondent)$75,000        0.93797   1.21994
## to $99,999                                                  
## as.factor(income_respondent)Less           0.00000   1.21994
## than $25,000                                                
## ------------------------------------------------------------
\end{verbatim}

To begin with,in Table 1, we display the output from the estimate of our
model using summary statistics via the MASS(reference call) package. In
order to interpret both the impact and the strength of our predictor
variables we will pay attention to three key columns of our regression
summary; Estimate, Z-value, and P-value. The coefficient estimate value
will tell us the log change in the total number of children that we
expect a respondent to have given change in the predictor's value. Next,
the Z-values will tell us whether or not we can reject the null
hypothesis, that our coefficient estimate is truly zero. Here, to
conform with a 95\% confidence interval, we will be looking for absolute
values greater than 1.96. Lastly, a predictor's p value works with the z
value to confirm our rejection of the null hypothesis. Keeping in line
with the same 95\% confidence interval we require values less than 0.05.
Independant variables that satisfy both of the Z and p conditions we
have described above, will in result reject the null hypothesis and
prove to be significant predictors of the total number of children
people have. We will discuss which specific predictors these are and
their overall significance in the discussion section below.

Below, in Figure \_\_\_\_ We display the estimated values of our
explanatory variables along with their standard errors as horizontal
lines plotting the upper and lower bounds to the estimates.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot_summs}\NormalTok{(negbinmodel, }\DataTypeTok{scale=} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{STA304PS3Rough3_files/figure-latex/unnamed-chunk-11-1.pdf}

Next, In Figure 1, we can see the estimated coefficient values and their
respective standard deviations. As described above, estimates are in
relation to the log change that we expect to have given a change in the
predictor variables.The standard deviation tracks the variability
between these estimates, and thus shows how precise they are. For age,
we observe that the standard deviation is very small and thus the
estimate of the coefficient is very precise. Next for the level of
education completed, we can see for the majority of categories, standard
deviation was relatively low and thus the estimate coefficient for these
categories is accurate. However, for ``University certificate or diploma
below the bachelor's level'', ``University certificate or diploma above
the bachelor's level'' and ``Trade certificate or diploma'' had higher
standard deviations than the other levels of education, thus we cannot
trust their estimated coefficients as surely. Finally, for levels of
annual income, we see that the standard deviation is relatively high in
comparison to education. The average s.d for income categories was about
0.0324 whereas education was only about 0.023, thus the estimate of the
coefficients for variables in this category were the most imprecise.

\hypertarget{interpretations}{%
\subsection{Interpretations}\label{interpretations}}

To interpret both the impact and the strength of our predictor variables
we will pay attention to three key columns of our regression summary;
Estimate, Z-value, and P-value. The coefficient estimate value will tell
us the log change in the total number of children that we expect a
respondent to have given a unit change in the predictor's value.
Z-values will tell us whether or not we can reject the null hypothesis,
that our coefficient estimate is truly zero. Here, to conform with a
95\% confidence interval, we will be looking for absolute values greater
than 1.96. Lastly, a predictor's p-value works with the z-value to
confirm our rejection of the null hypothesis. Keeping in line with the
same 95\% confidence interval we require values less than 0.05.

AGE: Estimate: 0.02415 With a coefficient estimate of 0.02415, this
means we would expect to see a 0.02415 change in the log value of the
total number of children in a family, given a one unit change in the
respondent's age. This suggests a positive relationship between a
respondent's age and the number of children in their family. When
thinking about the real world, having even one child is a lengthy
process and having more only requires a greater amount of time, this
result was to be expected. z and p values: z = 67.49285 \textgreater{}
1.96 p = 0.00000 \textless{} 0.05 As both these values completely
satisfy our conditions, we can safely reject the null hypothesis and
conclude that a respondent's age is a significant predictor of the total
number of children they have.

EDUCATION: - Estimates: These values are based off of a respondent that
has earned a Bachelor's degree. Thus we think about them as the
difference in the number of total children we expect to see from a
respondent with a different level of education. As we analyze the
coefficient estimates, we can begin to visualize a ranking of what level
of education will lead to the highest predicted number of children. We
first notice an obvious result, when compared to a Bachelor's degree
level of education, almost all other options lead us to expect a higher
number of children in a family. However, when respondents had achieved a
level of education above the Bachelor's level we can actually see a
decrease in the number of children expected. Looking more closely at the
estimated results, we can start to see a general trend, the higher the
level of education achieved, the fewer children we expect to see in the
family. Obtaining a trade school certificate or less than a high school
diploma resulted in the highest estimates at 0.18554 and 0.17617
respectively, suggesting that we would expect to see the most children
in these families. Conversely, earning a degree above a Bachelor's
results in the lowest coefficient estimate at -0.05890, and leading us
to expect the fewest amount of children in a respondent's family. Z and
p-values For all education options except a university certificate below
the bachelor's level, we see our z and p-values satisfying both
conditions, thus allowing us to confirm their significance and reject
the null hypothesis that their estimate values are zero. - Explain below
bachelor's level (maybe not a large population, have to look)

INCOME: - Estimates - Using the 100,000- 124,999 Income bracket as the
one we condition on, we can interpret the estimates from our income
categories as differences in the total number of children we expect in
the family of a respondent with an income between 100,000 and 124,999
per year. Analyzing the coefficient estimates for different income
categories suggests to us that, for the most part, having an income
below the 100,000- 124,999 bracket leads to a lower prediction of total
children in a family. As we can see, for income levels less than 25,000
and between 25,000- 49,999 their coefficient estimates are the lowest
when compared to the 100,000- 124,999 income bracket, sitting at
-0.18074 and -0.15031 respectively, suggesting that we would expect the
fewest number of children in these families. When we examine income
levels above 125,000 we see that we would actually expect a higher total
number of children in a family, with an estimate of 0.02369, this helps
to confirm the idea that lower levels of income lead to fewer children
in a family. Z and p values Examining the z and p-values of our income
brackets, we can see that for incomes; less than 25,000, between 25,000-
49,999, and between 50,000-74,999, both values satisfy the necessary
conditions, suggesting that we can confirm their significance and reject
the null hypothesis. For income brackets of more than 125,000 and
between 75,000-99,999, however, both values fail to satisfy the
conditions and so we cannot fully confirm or deny their significance. -
Reasons why? Have to look if there are any obvious

\hypertarget{weaknesses}{%
\section{Weaknesses}\label{weaknesses}}

\begin{itemize}
\tightlist
\item
  We notice that the number of respondents with 0 children was
\end{itemize}

The limitations of this article are mainly reflected in the biasedness
of data and methodological weaknesses. The biasedness of data collection
is mainly caused by the single data collection method. The data is
collected via phone. The biggest disadvantage of this collection method
is that it ignores many people who do not have mobile phones or have
multiple mobile phones. As the data shows, many of the respondents are
middle-aged, while the young who prefer face-to-face communication and
the elderly who cannot use mobile phones for various reasons are largely
ignored. In this paper, we use linear regression to explore the
relationship between age, income, education, and number of children. The
main limitation of Linear Regression is the assumption of linearity
between the dependent variable and the independent variables. In the
real world, the data is rarely linearly separable. It assumes that there
is a straight-line relationship between the dependent and independent
variables which is incorrect many times. Although the data sources are
reliable, there are inevitably some problems with such a large amount of
data. For example, respondents may respond less positively and
accurately to many long survey questions. Moreover, in this paper, a
large amount of data was removed when calling filter function which
results in a less predictable model. Therefore, to improve this paper,
we can reduce the length of questions and questionnaires to improve the
accuracy of data. Increase the method of data collection to ensure the
universality of data; And using better models to predict the results of
the data.

\end{document}
